/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface TestList {
        "items": any[];
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLTestListElement extends Components.TestList, HTMLStencilElement {
    }
    var HTMLTestListElement: {
        prototype: HTMLTestListElement;
        new (): HTMLTestListElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "test-list": HTMLTestListElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface TestList {
        "items"?: any[];
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "test-list": TestList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "test-list": LocalJSX.TestList & JSXBase.HTMLAttributes<HTMLTestListElement>;
        }
    }
}
