/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface AvatarComponent {
        "avatarURL": string;
        "refreshAvatar": () => Promise<void>;
        "size": string;
    }
    interface TestList {
        "items": any[];
        "loading": boolean;
        "searchTerm": string;
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAvatarComponentElement extends Components.AvatarComponent, HTMLStencilElement {
    }
    var HTMLAvatarComponentElement: {
        prototype: HTMLAvatarComponentElement;
        new (): HTMLAvatarComponentElement;
    };
    interface HTMLTestListElement extends Components.TestList, HTMLStencilElement {
    }
    var HTMLTestListElement: {
        prototype: HTMLTestListElement;
        new (): HTMLTestListElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "avatar-component": HTMLAvatarComponentElement;
        "test-list": HTMLTestListElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface AvatarComponent {
        "avatarURL"?: string;
        "size"?: string;
    }
    interface TestList {
        "items"?: any[];
        "loading"?: boolean;
        "searchTerm"?: string;
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "avatar-component": AvatarComponent;
        "test-list": TestList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "avatar-component": LocalJSX.AvatarComponent & JSXBase.HTMLAttributes<HTMLAvatarComponentElement>;
            "test-list": LocalJSX.TestList & JSXBase.HTMLAttributes<HTMLTestListElement>;
        }
    }
}
